### ISSUE TITLE
newbee... 

### ISSUE THREAD

**Issue by ronniebee** [benct/lovelace-xiaomi-vacuum-card#22]
I'm now working for one week with HA with no experience at all. But got it working from scratch. including my xiaomi vac (yes with the 32 position code)... Took me a while.  Now I cannot get the vac- card working. Made a ui-lovelace,yaml folder in my config and added the url.. But now got stuck. What am I doing wrong.

**Comment by benct** [comment]
I need a bit more info to know what the problem is.. Are you editing the yaml files directly in your file system or through the HA user interface? You need to enable yaml mode in `configuration.yaml` if you are not editing the interface directly in your browser:
```
lovelace:
  mode: yaml
```
When you have added the changes you should probably hit refresh in the HA menu. Or do a proper restart/reboot of your HA server. 

You could also have a closer look at how it is set up in [my config](https://github.com/benct/home-assistant-config). Other than that, I would read more of the [Lovelace docs](https://www.home-assistant.io/lovelace) for troubleshooting.

**Comment by ronniebee** [comment]
Hi Bent, thank you for your reply. That did the trick... lovelace yaml... As said, newbee.. 
Cheers!
