### ISSUE TITLE
Status and mode unavailable with template vacuum

### ISSUE THREAD

**Issue by CarterBrehm** [benct/lovelace-xiaomi-vacuum-card#31]
I used to use a series of rest commands and sensors to control my shark ion vacuum, but now I've grouped them together in a template vacuum entity and added this card. The battery portion works great, but both the status and mode say unavailable. Is there a fix? I'm using the `robovac` preset because that provides the closest featureset to the Ion.

**Comment by benct** [comment]
It probably won't just work out of the box, because I have to add support for different vendors and their different attributes and sensor keys. Similarly as with other vendors, can you copy the attributes that your vacuum entity provides (dev state) and a screenshot of the more-info dialog? See #16 for examples.
